/*http://listserv.uga.edu/cgi-bin/wa?A2=ind9907C&L=sas-l&P=R1337
Dorfman:

%LET LIST =
SG FJLKDSN GEWO OPITHUI GJSERO TNJEOWIJ TW9345Y TWES SDJGJSRL NWOITJN RET
POTREPOR _5TWT WPST NWP4 T924YW P9YTP9W4 NT599P DLKFGBLK SDGSGIW A AEG AEF ZG
EGH A G HA HESH AIT4Y8W3 HAW T83PTQ3Y O OYTP53YT PQYP8Y3Q SSLKGH SLIEUH AERH
DQLUEIUR SL SLSHIH4 AEK AH5WO TA AEH EU DJGLKDJ ERHISHKL QLR UHER GHSLHLSH
RBGHSD SLH SKEHRT RSKIEHB Q87O3WSL B SDKLQI WPE WEGIUQ HIHQPIG H QPGKLXK ZLQA
HQP GTHQPG Z AOIRPH PGT3Q PGHSE QAPUR HPQYPQ A XC N SLKG PZEAF RQIUH RS H
T38753QO SL KG OW7TY OQ HSL QP YOQ287 _W7 TOQR TL DSLSD YSIUYG RISWYG VQ369R4
ORA47Q3 Y94 Z Q374R R462QTQ;



%put %MLSORT2 (SORTIN=&LIST,SEQ=A,NODUP=N);
%put  %MLSORT2 (SORTIN=&LIST,SEQ=D,NODUP=N);
%put %MLSORT2 (SORTIN=&LIST,SEQ=A,NODUP=Y);
%put  %MLSORT2 (SORTIN=&LIST,SEQ=D,NODUP=Y);
*/


%MACRO MLSORT2 (SORTIN=,SEQ=A,NODUP=N,MSG=Y,LEN=8);
   %LOCAL COLL D DGT N POS PREVW SORTWK W;
   %IF &SEQ EQ A
      %THEN %LET COLL = *0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ_;
      %ELSE %LET COLL = *_ZYXWVUTSRQPONMLKJIHGFEDCBA9876543210;


   %DO N=1 %TO 38; %LOCAL P&N; %END;


   %DO POS=&LEN %TO 1 %BY -1;
      %LET N = 1;
      %LET W = %SCAN(&SORTIN,1);
      %DO %WHILE (&W NE);
         %LET DGT = %INDEX (&COLL,%SUBSTR(&W*******,&POS,1));
         %LET P&DGT = &&P&DGT &W;
         %LET N = %EVAL(&N+1);
         %LET W = %SCAN(&SORTIN,&N);
      %END;
      %LET SORTIN =;
      %DO J=1 %TO 38;
         %LET SORTIN = &SORTIN &&P&J;
         %LET P&J = ;
      %END;
   %END;


   %LET N = %EVAL(&N-1);
   %LET D = 0;
   %LET PREVW =;


   %IF &NODUP NE N %THEN %DO J=1 %TO &N;
       %LET W = %SCAN(&SORTIN,&J);
       %IF &W NE &PREVW %THEN %LET SORTWK = &SORTWK &W;
       %ELSE %LET D = %EVAL(&D+1);
       %LET PREVW = &W;
   %END;




   %IF &NODUP NE N %THEN &SORTWK;
   %ELSE                 &SORTIN;
%MEND MLSORT2;


